---
title: Jovan Savic Bridge the Gap Between Business Goals and Design
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  projects:
    title: Projects
    output: true
    permalink: "/:path/"
  uploads:
    title: Uploads
    output: true
email: mail@jovan.design
description: Jovan is UI/UX/Web designer working with Startups and also other companies
  that grow Startup-like culture on increasing landing page conversion and product
  user experience.
baseurl: ''
url: ''
github_username: johnofficial
behance_username: designedbyjovan
dribbble_username: designedbyjovan
instagram_username: designedbyjovan
facebook_username: designedbyjovan
twitter_username: designedbyjovan
linkedin_username: designedbyjovan
product_hunt_username: "@jovansavic"
site_theme: ''
markdown: kramdown
permalink: "/blog/:title/"
plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-paginate
include:
- _pages
paginate: 6
paginate_path: "/blog/:num/"
exclude:
- frasco.config.js
- Gemfile
- Gemfile.lock
- gulp_tasks
- gulpfile.js
- LICENSE
- node_modules
- npm-debug.log
- package.json
- package-lock.json
- README.md
- vendor/bundle/
- vendor/cache/
- vendor/gems/
- vendor/ruby/
- yarn.lock
